import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:healr/core/constants.dart';
import 'package:healr/core/utils/styles.dart';
import 'package:healr/features/profile/presentation/views/widgets/custom_app_bar.dart';

class PrivacyPolicyViewBody extends StatelessWidget {
  const PrivacyPolicyViewBody({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: SafeArea(
          child: Padding(
            padding: EdgeInsets.symmetric(
              horizontal: 16.w,
              vertical: 16.h,
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const CustomAppBar(text: 'Privacy & Terms'),
                SizedBox(height: 24.h),
                _buildAnimatedSection(
                  context,
                  title: 'AI Healr Bot Policy',
                  content:
                      'Healr’s AI chatbot is designed to support general health-related questions and guide users with basic information.\n\n'
                      'Please keep in mind:\n'
                      '- The chatbot does not provide a diagnosis or medical treatment.\n'
                      '- Responses are generated by AI and may not be 100% accurate or complete.\n'
                      '- For urgent or serious medical issues, always consult a licensed medical professional.\n'
                      '- User inputs may be used anonymously to improve our AI engine.\n'
                      '- Misusing the bot (e.g., offensive or misleading use) may lead to restrictions.\n\n'
                      'By using the chatbot, you confirm that you understand and accept these terms.',
                  icon: Icons.smart_toy_rounded,
                  delay: 200,
                ),
                SizedBox(height: 24.h),
                _buildAnimatedSection(
                  context,
                  title: 'Terms & Conditions',
                  content: 'Last Updated: April 11, 2025\n\n'
                      'Welcome to Healr! These Terms & Conditions govern your use of the Healr mobile application. By using the app, you agree to the following terms:\n\n'
                      '1. Acceptance of Terms\n'
                      '   - You must be at least 13 years old to use Healr.\n'
                      '   - If you’re using Healr on behalf of an organization, you confirm you have permission to do so.\n\n'
                      '2. Use of the App\n'
                      '   - Permitted: Manage your health data (name, email, symptoms, etc.).\n'
                      '   - Prohibited: Illegal use, tampering, hacking, harassment, reverse-engineering.\n\n'
                      '3. User Responsibilities\n'
                      '   - Ensure your info is accurate.\n'
                      '   - You’re responsible for securing your device.\n'
                      '   - Make sure your device supports the app.\n\n'
                      '4. Intellectual Property\n'
                      '   - All content belongs to Healr or its licensors.\n'
                      '   - You may not copy or modify the app or its content.\n\n'
                      '5. Disclaimer\n'
                      '   - The app is provided "as-is".\n'
                      '   - Healr does not offer medical advice. Always consult a doctor.\n\n'
                      '6. Limitation of Liability\n'
                      '   - Healr is not liable for indirect damages (data loss, injury, etc.).\n\n'
                      '7. Termination\n'
                      '   - You can uninstall anytime. We can suspend or terminate access if terms are violated.\n\n'
                      '8. Changes\n'
                      '   - Terms may change. Continued use = acceptance.\n\n'
                      '9. Governing Law\n'
                      '   - Governed by the laws of Egypt (or your country).',
                  icon: Icons.gavel_rounded,
                  delay: 400,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildAnimatedSection(
    BuildContext context, {
    required String title,
    required String content,
    required IconData icon,
    required int delay,
  }) {
    return AnimatedOpacity(
      opacity: 1.0,
      duration: Duration(milliseconds: 500 + delay),
      curve: Curves.easeInOut,
      child: Card(
        color: kPrimaryColor,
        elevation: 4,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16.r),
        ),
        child: Padding(
          padding: EdgeInsets.all(16.w),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Icon(
                    icon,
                    size: 28.sp,
                    color: kSecondaryColor,
                  ),
                  SizedBox(width: 12.w),
                  Expanded(
                    child: Text(
                      title,
                      style: Styles.textStyle20.copyWith(
                        fontWeight: FontWeight.w700,
                        color: kSecondaryColor,
                      ),
                    ),
                  ),
                ],
              ),
              SizedBox(height: 8.h),
              Divider(
                color: kSecondaryColor.withOpacity(0.2),
                thickness: 1,
              ),
              SizedBox(height: 16.h),
              Text(
                content,
                style: Styles.textStyle14.copyWith(
                  height: 1.8,
                  color: kSignIconColor,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
